apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  labels:
    app: flask-api
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
        k8s-app: flask-api
    spec:
      containers:
        - name: flask-api
          image: igortab/flask-api:ac52ae1ca9a7ed0cca7bcfb1d960948bd353eb01
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api
spec:
  type: LoadBalancer
  selector:
    app: flask-api
    k8s-app: flask-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000